introduce new add command for new function bean

diff --git a/springfun b/springfun
--- a/springfun
+++ b/springfun
@@ -2,10 +2,9 @@
 
 VERSION="0.0.1"
 
-declare -a CE_TYPE
-declare -a A_FUN
-declare -a A_TYPE
-declare -a A_SCHEMA
+FUN=""
+CE_TYPE=""
+CE_SCHEMA=""
 
 function print_usage() {
 cat <<EOF
@@ -13,53 +12,46 @@ springfun is for Spring Functions on Knative
 version $VERSION
 
 Commands:
-  init         Initialize a function
-  build        Build a function container
-  run          Run a function container
-  delete       Delete a function container
+  init         Initialize a function project
+  add          Add a function to the project
+  build        Build a function project container
+  run          Run a function project container
+  delete       Delete a function project container
 
 EOF
 }
 
+function ce_types() {
+  if [[ $CE_TYPE != "" ]]; then
+    if [[ $CE_SCHEMA == "" ]]; then
+      echo "looking up schema via type $CE_TYPE"
+      CE_SCHEMA="$(kubectl get eventtype $CE_TYPE -n default -ojsonpath='{.spec.schema}')"
+      if [[ $CE_SCHEMA == "" ]]; then
+        echo "ERROR: unable to find schema for $CE_TYPE"
+        exit 1
+      else
+        echo "using schema: $CE_SCHEMA"
+      fi
+    fi
+  fi
+}
+
+pushd () {
+    command pushd "$@" > /dev/null
+}
+
+popd () {
+    command popd "$@" > /dev/null
+}
+
 function init() {
   if [[ $NAME == "" ]]; then
-    echo "ERROR: function name must be specified"
+    echo "ERROR: project name must be specified"
     exit 1
   fi
   if [[ -d $NAME ]]; then
-    echo "ERROR: the $NAME function already exists"
+    echo "ERROR: the $NAME project already exists"
     exit 1
-  fi
-  if [[ ${#CE_TYPE[@]} > 0 ]]; then
-    for i in "${!CE_TYPE[@]}"; do 
-      INFO=(${CE_TYPE[$i]//:/ })
-      if [[ ${#INFO[@]} < 1 ]]; then
-        echo "ERROR: type not specified: ${CE_TYPE[$i]}"
-        exit 1
-      fi
-      A_TYPE+=(${INFO[0]})
-      if [[ ${INFO[1]} == "" ]]; then
-        A_FUN+=("fun${i}")
-      else
-        A_FUN+=(${INFO[1]})
-      fi
-      A_SCHEMA+=(${INFO[2]})
-      schema=(${INFO[2]})
-      if [[ $schema == "" ]]; then
-        type=${INFO[0]}
-        echo "looking up schema via type $type"
-        schema="$(kubectl get eventtype $type -n default -ojsonpath='{.spec.schema}')"
-        if [[ $schema == "" ]]; then
-          echo "ERROR: unable to find schema for $type"
-          exit 1
-        else
-          echo "using schema: $schema"
-          A_SCHEMA+=($schema)
-        fi
-      fi
-    done
-  else
-    A_FUN+=("fun")
   fi
   
   # start.spring.io
@@ -75,56 +67,6 @@ function init() {
    -d packageName=com.example.$NAME \
    -d baseDir=$NAME | tar -xzvf -
 
-  if [[ ${#A_TYPE[@]} > 0 ]]; then
-    # CE dep
-    mv $NAME/pom.xml $NAME/pom.xml.tmp
-    sed "s/^	<\/dependencies>/		<dependency>+			<groupId>io.cloudevents<\/groupId>+			<artifactId>cloudevents-api<\/artifactId>+			<version>1.2.0<\/version>+		<\/dependency>+	<\/dependencies>/" $NAME/pom.xml.tmp | tr '+' '\n' > $NAME/pom.xml
-    rm $NAME/pom.xml.tmp
-
-    # jsonschema2pojo
-    mv $NAME/pom.xml $NAME/pom.xml.tmp
-    sed "s/^		<\/plugins>/			<plugin>+				<groupId>org.jsonschema2pojo<\/groupId>+				<artifactId>jsonschema2pojo-maven-plugin<\/artifactId>+				<version>1.0.2<\/version>+				<configuration>+					<sourceDirectory>\${basedir}\/src\/main\/resources\/schema<\/sourceDirectory>+					<targetPackage>com.example.types<\/targetPackage>+				<\/configuration>+				<executions>+					<execution>+						<goals>+							<goal>generate<\/goal>+						<\/goals>+					<\/execution>+				<\/executions>+			<\/plugin>+		<\/plugins>/" $NAME/pom.xml.tmp | tr '+' '\n' > $NAME/pom.xml
-    rm $NAME/pom.xml.tmp
-
-    # schema
-    mkdir -p $NAME/src/main/resources/schema
-    pushd $PWD
-    cd $NAME/src/main/resources/schema/
-    for i in "${!A_SCHEMA[@]}"; do
-      wget ${A_SCHEMA[$i]}
-    done
-    popd
-
-    # mapper
-    mkdir -p $NAME/src/main/java/com/springdeveloper/support/cloudevents
-    curl https://raw.githubusercontent.com/trisberg/cloud-event-mapper/master/src/main/java/com/springdeveloper/support/cloudevents/CloudEventMapper.java \
-      -o $NAME/src/main/java/com/springdeveloper/support/cloudevents/CloudEventMapper.java
-  fi
-
-  # add fun bean
-  pushd $PWD
-  cd $NAME/src/main/java/com/example/${NAME//-}
-  MAIN_FILE=$(ls)
-  mv $MAIN_FILE $MAIN_FILE.tmp
-  sed -i .bak "s/import org.springframework.boot.SpringApplication;/import java.util.function.Function;++import org.springframework.boot.SpringApplication;/" $MAIN_FILE.tmp
-  sed -i .bak "s/import org.springframework.boot.autoconfigure.SpringBootApplication;/import org.springframework.boot.autoconfigure.SpringBootApplication;+import org.springframework.context.annotation.Bean;/" $MAIN_FILE.tmp
-  cat $MAIN_FILE.tmp | tr '+' '\n' > $MAIN_FILE
-  rm $MAIN_FILE.tmp
-  for i in "${!A_FUN[@]}"; do
-    fun=${A_FUN[$i]}
-    mv $MAIN_FILE $MAIN_FILE.tmp
-    sed -i .bak "s/	public static void main(String\[\] args) {/	@Bean+	public Function<String, String> ${fun}() {+		return (in) -> {+			return in;+		};+	}++	public static void main(String\[\] args) {/" $MAIN_FILE.tmp
-    cat $MAIN_FILE.tmp | tr '+' '\n' > $MAIN_FILE
-    rm $MAIN_FILE.tmp
-  done
-  rm $MAIN_FILE.tmp.bak
-  popd
-
-  # resolve deps
-  cd $NAME
-  ./mvnw compile
-  cd ..
-
   # knative service
 cat <<EOF > $NAME/knative-service.yaml
 apiVersion: serving.knative.dev/v1
@@ -139,31 +81,6 @@ spec:
         - image: $NAME
 EOF
 
-if [[ ${#A_TYPE[@]} > 0 ]]; then
-  for i in "${!A_FUN[@]}"; do
-    fun=${A_FUN[$i]}
-    type=${A_TYPE[$i]}
-    # knative trigger
-cat <<EOF >> $NAME/knative-trigger.yaml
----
-apiVersion: eventing.knative.dev/v1beta1
-kind: Trigger
-metadata:
-  name: $NAME-$fun
-spec:
-  filter:
-    attributes:
-      type: $type
-  subscriber:
-    ref:
-      apiVersion: serving.knative.dev/v1
-      kind: Service
-      name: $NAME
-    uri: $fun
-EOF
-  done
-fi
-
   # skaffold
   cd $NAME
   skaffold init --skip-build --force=true
@@ -174,13 +91,115 @@ fi
 
 }  
 
-function build() {
+function add() {
   if [[ $NAME == "" ]]; then
-    echo "ERROR: function name must be specified"
+    echo "ERROR: project name must be specified"
     exit 1
   fi
   if [[ ! -d $NAME ]]; then
-    echo "ERROR: can not find the $NAME function"
+    echo "ERROR: can not find the $NAME project"
+    exit 1
+  fi
+  if [[ $NAME == "" ]]; then
+    echo "ERROR: function name is required, use the '--function' option"
+    exit 1
+  fi
+
+  ce_types
+
+  if [[ $CE_TYPE != "" ]]; then
+
+    # look for cloudevents
+    ce_defined=$(grep -i 'cloudevents' $NAME/pom.xml --count)
+
+    if [[ $ce_defined == 0 ]]; then
+      echo "CE dep: $ce_defined"
+      # CE dep
+      mv $NAME/pom.xml $NAME/pom.xml.tmp
+      sed "s/^	<\/dependencies>/		<dependency>+			<groupId>io.cloudevents<\/groupId>+			<artifactId>cloudevents-api<\/artifactId>+			<version>1.2.0<\/version>+		<\/dependency>+	<\/dependencies>/" $NAME/pom.xml.tmp | tr '+' '\n' > $NAME/pom.xml
+      rm $NAME/pom.xml.tmp
+
+      # jsonschema2pojo
+      mv $NAME/pom.xml $NAME/pom.xml.tmp
+      sed "s/^		<\/plugins>/			<plugin>+				<groupId>org.jsonschema2pojo<\/groupId>+				<artifactId>jsonschema2pojo-maven-plugin<\/artifactId>+				<version>1.0.2<\/version>+				<configuration>+					<sourceDirectory>\${basedir}\/src\/main\/resources\/schema<\/sourceDirectory>+					<targetPackage>com.example.types<\/targetPackage>+				<\/configuration>+				<executions>+					<execution>+						<goals>+							<goal>generate<\/goal>+						<\/goals>+					<\/execution>+				<\/executions>+			<\/plugin>+		<\/plugins>/" $NAME/pom.xml.tmp | tr '+' '\n' > $NAME/pom.xml
+      rm $NAME/pom.xml.tmp
+
+      # mapper
+      mkdir -p $NAME/src/main/java/com/springdeveloper/support/cloudevents
+      curl https://raw.githubusercontent.com/trisberg/cloud-event-mapper/master/src/main/java/com/springdeveloper/support/cloudevents/CloudEventMapper.java \
+        -o $NAME/src/main/java/com/springdeveloper/support/cloudevents/CloudEventMapper.java
+
+      # schema
+      mkdir -p $NAME/src/main/resources/schema
+      pushd $PWD
+      cd $NAME/src/main/resources/schema/
+      wget $CE_SCHEMA
+      popd
+
+        # resolve deps
+        cd $NAME
+        ./mvnw compile
+        cd ..
+    fi
+
+  # knative trigger
+cat <<EOF >> $NAME/knative-trigger.yaml
+---
+apiVersion: eventing.knative.dev/v1beta1
+kind: Trigger
+metadata:
+  name: $NAME-$FUN
+spec:
+  filter:
+    attributes:
+      type: $CE_TYPE
+  subscriber:
+    ref:
+      apiVersion: serving.knative.dev/v1
+      kind: Service
+      name: $NAME
+    uri: $FUN
+EOF
+
+    # look for skaffold trigger manifest
+    trigger_defined=$(grep -i 'knative-trigger' $NAME/skaffold.yaml --count)
+    if [[ $trigger_defined == 0 ]]; then
+      cd $NAME
+      skaffold init --skip-build --force=true
+      mv ./skaffold.yaml ./skaffold.yaml.tmp
+      sed "s/deploy:/build:+  local:+    push: true+  artifacts:+    - image: $NAME+      buildpack:+        builder: 'cloudfoundry\/cnb:bionic'+  tagPolicy:+    sha256: {}+deploy:/" ./skaffold.yaml.tmp | tr '+' '\n' > ./skaffold.yaml
+      rm ./skaffold.yaml.tmp
+      cd ..
+    fi
+  fi
+
+  # add fun bean
+  pushd $PWD
+  cd $NAME/src/main/java/com/example/${NAME//-}
+  MAIN_FILE=$(ls)
+  beans_defined=$(grep -i '@Bean' $MAIN_FILE --count)
+  if [[ $beans_defined == 0 ]]; then
+    mv $MAIN_FILE $MAIN_FILE.tmp
+    sed -i "s/import org.springframework.boot.SpringApplication;/import java.util.function.Function;++import org.springframework.boot.SpringApplication;/" $MAIN_FILE.tmp
+    sed -i "s/import org.springframework.boot.autoconfigure.SpringBootApplication;/import org.springframework.boot.autoconfigure.SpringBootApplication;+import org.springframework.context.annotation.Bean;/" $MAIN_FILE.tmp
+    cat $MAIN_FILE.tmp | tr '+' '\n' > $MAIN_FILE
+    rm $MAIN_FILE.tmp
+  fi
+  mv $MAIN_FILE $MAIN_FILE.tmp
+  sed -i "s/	public static void main(String\[\] args) {/	@Bean+	public Function<String, String> ${FUN}() {+		return (in) -> {+			return in;+		};+	}++	public static void main(String\[\] args) {/" $MAIN_FILE.tmp
+  cat $MAIN_FILE.tmp | tr '+' '\n' > $MAIN_FILE
+  rm $MAIN_FILE.tmp
+  popd
+
+}  
+
+function build() {
+  if [[ $NAME == "" ]]; then
+    echo "ERROR: project name must be specified"
+    exit 1
+  fi
+  if [[ ! -d $NAME ]]; then
+    echo "ERROR: can not find the $NAME project"
     exit 1
   fi
   pushd $PWD
@@ -191,11 +210,11 @@ function build() {
 
 function run() {
   if [[ $NAME == "" ]]; then
-    echo "ERROR: function name must be specified"
+    echo "ERROR: project name must be specified"
     exit 1
   fi
   if [[ ! -d $NAME ]]; then
-    echo "ERROR: can not find the $NAME function"
+    echo "ERROR: can not find the $NAME project"
     exit 1
   fi
   pushd $PWD
@@ -206,11 +225,11 @@ function run() {
 
 function delete() {
   if [[ $NAME == "" ]]; then
-    echo "ERROR: function name must be specified"
+    echo "ERROR: project name must be specified"
     exit 1
   fi
   if [[ ! -d $NAME ]]; then
-    echo "ERROR: can not find the $NAME function"
+    echo "ERROR: can not find the $NAME project"
     exit 1
   fi
   pushd $PWD
@@ -238,12 +257,16 @@ do
   if [[ $1 == -* ]]; then
     key="$1"
     case ${key} in
+      -f|--function)
+        FUN=$2
+      shift
+      ;;
       -t|--ce-type)
-        CE_TYPE+=($2)
+        CE_TYPE=$2
       shift
       ;;
       -s|--ce-schema)
-      CE_SCHEMA+=($2)
+        CE_SCHEMA=$2
       shift
       ;;
       *)
@@ -267,6 +290,8 @@ done
 
 if [[ "${COMMAND}" == "init" ]]; then
   init
+elif [[ "${COMMAND}" == "add" ]]; then
+  add
 elif [[ "${COMMAND}" == "build" ]]; then
   build
 elif [[ "${COMMAND}" == "run" ]]; then
